version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: safety_audit_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: safety_audit_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 